# All the eye images
path_to_image_directory: jeff_bezos
path_to_image_memmap: bezos_31.dat

# The dimensions of the image (should be the same as the monitor)
height: 1324
width: 900

# For large image sets (> 50) increate the stride so transitions are faster.
stride: 1

# Show the debug video?
debug: False

path_to_background_image: jeff_bezos/16.png
